export const ActionTypes = {
  SET_PRODUCTS: "SET_PRODUCTS",
  ADD_BASKET_ITEM: "ADD_BASKET_ITEM",
  REMOVE_BASKET_ITEM: "REMOVE_BASKET_ITEM",
  ORDER_ITEM: "ORDER_ITEM",
  GET_USER: "GET_USER",
  REMOVE_ORDER:'REMOVE_ORDER',
  SEARCH_ORDER:"SEARCH_ORDER"
};